:PROPERTIES:
:ID:       54e201d2-8f06-4072-bf68-f47c8672e48a
:END:
#+title: Project structure
#+filetags: :Sydc:

* Repo structure
** =sydml=
*** =app=
*** =src=
*** =test=
** =presydml=
** =vendor=
Vendored dependencies.
*** =tree-sitter=
The tree-sitter bindings for Haskell leave a lot to be desired. My patches
include the following:
- Add binding to =ts_node_string()=.
- Add bindings to the "edit" API.
*** =qbe=
This library provides a Haskell representation of QBE's IL. Patches include the
following:
- Bump the version bounds of =base=, =text=, =bytestring=, and =deepseq=.
- Add support for allocation instructions. This patch is the work of [[https://todo.sr.ht/~fgaz/qbe-hs/1][Ellis
  Kesterton]], whose merge request to =qbe-hs= has been idle upstream for over a
  year.
*** =compiler-explorer=
Commonly known as Godbolt. A tool for viewing compiler output and IRS. My
patches include:
- Add a Nix flake.
- Add support for presydml.
** =doc=
Documentation. Currently, this solely serves as a home for the rendered HTML of the README.
** =tree-sitter-sydml=
Houses Sydc's parser.
