cabal-version:   3.0
name:            sydml
version:         0.1.0.0
synopsis:        A compiler for an ML in Haskell's clothes.
description:     A compiler for an ML in Haskell's clothes.
license:         GPL-3.0-only
license-file:    LICENSE
author:          crumbtoo
maintainer:      lomiskiam@gmail.com

-- copyright:
category:        Language
build-type:      Simple
extra-doc-files: CHANGELOG.md

-- extra-source-files:

common common
  ghc-options:        -Wno-typed-holes

  -- -Wall
  default-extensions:
    BlockArguments
    DataKinds
    DeriveGeneric
    DeriveTraversable
    DerivingVia
    FlexibleContexts
    GADTs
    GeneralisedNewtypeDeriving
    LambdaCase
    MultiWayIf
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    PartialTypeSignatures
    PatternSynonyms
    StandaloneDeriving
    TypeApplications
    TypeFamilies

  ghc-options:        -fdefer-typed-holes
  default-language:   GHC2021

--------------------------------------------------------------------------------
-- sydml

library
  import:           common

  -- cabal-fmt: expand sydml/src/ -Main
  exposed-modules:
    Data.Located
    Data.PrettyP
    Effect.Unique
    Language.ANF.ClosureConvert
    Language.ANF.Hoist
    Language.ANF.LowerToQBE
    Language.ANF.Syntax
    Language.Core.LowerToANF
    Language.Core.Syntax
    Language.Core.Typecheck
    Language.Shared
    Language.SydML.LowerToCore
    Language.SydML.Parse
    Language.SydML.Syntax
    Language.SydML.Typecheck
    Sydc
    Sydc.Command.Batch
    Sydc.Driver
    Sydc.Error
    Sydc.Monad
    Sydc.Name
    Sydc.Query
    Sydc.Types
    SydPrelude

  default-language: GHC2021

  -- include-dirs:     tree-sitter-sydml/src
  -- includes:         tree_sitter/parser.h
  -- install-includes: tree_sitter/parser.h
  -- cxx-sources:      tree-sitter-sydml/src/parser.c
  build-depends:
    , base                       ^>=4.19.1.0
    , bytestring
    , comonad
    , containers
    , data-fix
    , dependent-hashmap
    , dependent-sum-template     ^>=0.2.0.1
    , deriving-compat
    , effectful
    , filepath
    , free
    , generic-lens               ^>=2.2.0.0
    , hashable
    , lens                       >=5.3.0     && <6.0.0
    , lsp
    , megaparsec
    , monadic-recursion-schemes
    , mtl
    , parser-combinators
    , pretty-simple
    , prettyprinter
    , qbe
    , recursion-schemes          >=5.0.0     && <6.0.0.0
    , rock                       >=0.3.1.0   && <0.4.0.0.0
    , semigroupoids
    , some
    , text                       >=2.0       && <2.2
    , text-short
    , these
    , transformers
    , tree-sitter
    , tree-sitter-sydml
    , unordered-containers
    , witherable

  hs-source-dirs:   sydml/src

executable sydc
  import:           common
  main-is:          Main.hs
  default-language: GHC2021
  other-modules:    Command.Batch

  -- other-extensions:
  build-depends:
    , base                  ^>=4.19.1.0
    , lens
    , optparse-applicative
    , sydml

  hs-source-dirs:   sydml/app

test-suite sydml-test
  import:         common
  type:           exitcode-stdio-1.0
  hs-source-dirs: sydml/test
  main-is:        Main.hs
  other-modules:  SydmlTests.EmptyInput
  build-depends:
    , base           ^>=4.19.1.0
    , sydml
    , tasty          >=1.2.2     && <1.6
    , tasty-golden   ^>=2.3
    , tasty-hunit    ^>=0.10
    , tasty-program  >=1.1       && <1.2.0

--------------------------------------------------------------------------------
-- presydc

library presydml
  import:           common

  -- cabal-fmt: expand presydml/src/ -Main
  exposed-modules:
    ANF
    Lam.Parse
    Lam.Syntax
    SSA
    SydPrelude

  default-language: GHC2021
  build-depends:
    , aeson
    , base                  ^>=4.19.1.0
    , bytestring
    , containers
    , effectful
    , generic-lens          ^>=2.2.0.0
    , hashable
    , lens                  >=5.3.0     && <6.0.0
    , megaparsec
    , mtl
    , parser-combinators
    , pretty-simple
    , prettyprinter
    , qbe
    , rock                  >=0.3.1.0   && <0.4.0.0.0
    , semigroupoids
    , text                  >=2.0       && <2.2
    , text-short
    , transformers
    , unordered-containers

  hs-source-dirs:   presydml/src

executable presydc
  hs-source-dirs:   presydml/app
  main-is:          Main.hs
  default-language: GHC2021
  build-depends:
    , aeson
    , base                  ^>=4.19.1.0
    , effectful
    , generic-lens          ^>=2.2.0.0
    , lens                  >=5.3.0     && <6.0.0
    , optparse-applicative
    , presydml
    , pretty-simple
    , prettyprinter
    , process
    , qbe
    , rock                  >=0.3.1.0   && <0.4.0.0.0
    , text                  >=2.0       && <2.2
    , unordered-containers
