name: Org Export

on:
  push:
    branches: [ main ]
  pull_request:
    branches: []
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Export Org files to GitHub Pages
      uses: tecosaur/org-knit-action@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # branch: gh-pages
